import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import Navbar from './ui/Navbar';
import BottomNav from './ui/BottomNav';

const roboto = Roboto({
    variable: '--font-robot',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.variable} antialiased`}>
                <Toaster
                    richColors={true}
                    closeButton={true}
                    position="top-right"
                />
                <Navbar />
                <main className="h-screen">{children}</main>
                <BottomNav />
            </body>
        </html>
    );
}
